apps/activities/urls.py
from django.urls import path
from . import views
from .views import (ActivityListView, ActivityCreateView, ActivityUpdateView, ActivityDeleteView,
                    ActivityCommentUpdateView, ActivityCommentDeleteView)

urlpatterns = [
    path('activities/', ActivityListView.as_view(), name='activities'),
    path('activities/new/', ActivityCreateView.as_view(), name='activity-create'),
    path('activity/<int:pk>/', views.activity_detail, name='activity-detail'),
    path('activities/<int:pk>/update/', ActivityUpdateView.as_view(), name='activity-update'),
    path('activities/<int:pk>/delete/', ActivityDeleteView.as_view(), name='activity-delete'),
    path('activities/comment/<int:pk>/update/',
         ActivityCommentUpdateView.as_view(), name='activitycomment-update'),
    path('activities/comment/<int:pk>/delete/',
         ActivityCommentDeleteView.as_view(), name='activitycomment-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.bouygue.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.agenda.urls')),
    path('', include('apps.blog.urls')),
    path('', include('apps.activities.urls')),
    path('', include('apps.info.urls')),
    path('', include('apps.work.urls')),
    path('', include('apps.budget.urls')),
]

handler400 = 'apps.bouygue.views.bad_request'
handler403 = 'apps.bouygue.views.permission_denied'
handler404 = 'apps.bouygue.views.page_not_found'
handler500 = 'apps.bouygue.views.server_error'

apps/activities/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _
from apps.users.models import MyUser


class Activity(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("Titre"))
    content = models.TextField(verbose_name=_("Description"))
    content2 = models.TextField(blank=True, verbose_name=_("Précisions"))
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    difficulty = models.SmallIntegerField(
        default=0,
        choices=[(0, "Très facile"), (1, "Facile"), (2, "Moyen"),
                 (3, "Difficile"), (4, "Très difficile")],
        verbose_name=_("Difficulté"),
    )
    duration = models.CharField(max_length=20, verbose_name=_("Durée"))
    distance = models.CharField(max_length=20, verbose_name=_("Temps de route"))
    image = models.ImageField(blank=True, upload_to="activities")
    image2 = models.ImageField(blank=True, upload_to="activities")

    class Meta:
        verbose_name_plural = "Activities"
        ordering = ["-date_posted"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("activity-detail", kwargs={"pk": self.pk})


class ActivityComment(models.Model):
    content = models.TextField(verbose_name=_(''))
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="comments")

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return str(self.author)

    def get_absolute_url(self):
        return reverse("activity-detail", kwargs={"pk": self.activity.pk})

apps/activities/forms.py
from django import forms
from .models import ActivityComment
from client_side_image_cropping import ClientsideCroppingWidget


class ActivityCommentForm(forms.ModelForm):
    class Meta:
        model = ActivityComment
        fields = ['content', 'image']
        widgets = {
            'image': ClientsideCroppingWidget(
                width=1000,
                height=600,
                preview_width=120,
                preview_height=72,
            )
        }

apps/activities/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from client_side_image_cropping import ClientsideCroppingWidget
from apps.users.models import MyUser
from .models import Activity, ActivityComment
from .forms import ActivityCommentForm


class ActivityListView(LoginRequiredMixin, ListView):
    model = Activity
    template_name = 'activities/activities.html'
    context_object_name = 'activities'
    ordering = ['-date_posted']
    paginate_by = 7

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        user.activities_viewed = len(Activity.objects.all())
        if user.is_authenticated and user.is_active:
            user.save()
        return super().dispatch(request, *args, **kwargs)


@login_required
def activity_detail(request, pk):
    template_name = 'activities/activity-detail.html'
    activity = get_object_or_404(Activity, pk=pk)
    author = request.user
    new_comment = None

    if request.method == 'POST':
        form = ActivityCommentForm(data=request.POST)
        if form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = form.save(commit=False)
            # Assign the current post and author to the comment
            new_comment.activity = activity
            new_comment.author = author
            # Save the comment to the database
            new_comment.save()
            messages.success(request, str("Commentaire publié."))
        form = ActivityCommentForm()
    else:
        form = ActivityCommentForm()

    # Paginator
    comments = activity.activitycomment_set.all()
    comment_count = len(comments)
    paginator = Paginator(comments, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, template_name, {
        'title': 'Activité', 'activity': activity, 'form': form,
        'page_obj': page_obj, 'comment_count': comment_count})


class ActivityCreateView(LoginRequiredMixin, CreateView):
    model = Activity
    template_name = 'activities/activity-create.html'
    fields = ['title', 'image', 'content', 'image2',
              'content2', 'difficulty', 'duration', 'distance']

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        form.fields['image'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        form.fields['image2'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ActivityUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Activity
    template_name = 'activities/activity-update.html'
    fields = ['title', 'image', 'content', 'image2',
              'content2', 'difficulty', 'duration', 'distance']

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        form.fields['image'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        form.fields['image2'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, str("L'activité a bien été modifiée."))
        return super().form_valid(form)

    def test_func(self):
        activity = self.get_object()
        user = self.request.user
        if user == activity.author or user.is_superuser or user.is_staff:
            return True
        return False


class ActivityDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Activity
    template_name = 'activities/activity-delete.html'
    context_object_name = 'activity'

    def get_success_url(self):
        messages.success(self.request, str("L'activité a bien été supprimée."))
        return '/activities/'

    def test_func(self):
        activity = self.get_object()
        user = self.request.user
        if user == activity.author or user.is_superuser or user.is_staff:
            return True
        return False


class ActivityCommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ActivityComment
    template_name = 'activities/activitycomment-update.html'
    fields = ['content', 'image']

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        form.fields['image'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, str("Le commentaire a bien été modifié."))
        return super().form_valid(form)

    def test_func(self):
        activity = self.get_object()
        if self.request.user == activity.author:
            return True
        return False


class ActivityCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ActivityComment
    template_name = 'activities/activitycomment-delete.html'
    context_object_name = 'comment'

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            messages.success(self.request, str("Le commentaire a bien été supprimé."))
            return next_url  # return next url for redirection
        return '/activities/'  # return some other url if next parameter not present

    def test_func(self):
        activity = self.get_object()
        user = self.request.user
        if user == activity.author or user.is_superuser or user.is_staff:
            return True
        return False

apps/activities/templates/activities/activities.html
{% extends "bouygue/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div hidden>{% block title %} - Activités {% endblock %}</div>
<!-- Page Header-->
<header class="page-header page-header-dark bg-img-cover overlay overlay-60" style="background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/castillou.jpg' %}); height: 19rem;">
    <div class="page-header-content">
        <div class="container text-center">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <h1 class="page-header-title mb-3">Activités</h1>
                    <p class="page-header-text mb-0">Consultez les idées d'activités, ou ajoutez la votre !</p>
                </div>
            </div>
        </div>
    </div>
    {% block border-wave %}
        {% include 'blocks/svg-border-wave.html' %}
    {% endblock %}
</header>
<section class="bg-light py-4 mb-2">
    <div class="container" style="padding-left: 1.5rem; padding-right: 1.5rem;">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <div class="post-archive-tag">
            <a class="btn btn-primary font-weight-bolder mt-1" href="{% url 'bouygue-home' %}" title="retour" ><i class="fas fa-chevron-left dropdown-arrow"></i></a>
            <a class="btn btn-primary font-weight-700 mt-1" href="{% url 'activity-create' %}" name="new">Nouvelle Activité</a>
        </div>
        {% if activities %}
        <a class="card post-preview post-preview-featured lift mb-5" href="{% url 'activity-detail' activities.first.id %}">
            <div class="row no-gutters">
                {% if activities.first.image %}
                    <div class="col-lg-5"><div class="post-preview-featured-img" style="background-image: url('{{ activities.first.image.url }}')"></div></div>
                {% else %}
                    <div class="col-lg-5"><div class="post-preview-featured-img" style="background-image: url({% static 'bouygue/assets/img/activity_default.jpg' %})"></div></div>
                {% endif %}
                <div class="col-lg-7">
                    <div class="card-body-activities-first">
                        <div class="py-4 card-body-activities">
                            <h5 class="card-title" style="font-size: 108%;">{{ activities.first.title }}</h5>
                            <p class="card-text-2 mt-4">Difficulté : {{ activities.first.get_difficulty_display }}</p>
                            <p class="card-text-2">Durée : {{ activities.first.duration }}</p>
                            <p class="card-text-2">Temps de route : {{ activities.first.distance }}</p>
                        </div>
                        <hr />
                        <div class="post-preview-meta">
                            <img class="post-preview-meta-img" src="{{ activities.first.author.profile.image.url }}" />
                            <div class="post-preview-meta-details">
                                <div class="post-preview-meta-details-name {% if activies.first.author.is_superuser or activities.first.author.is_staff %} text-purple {% endif %}">{{ activities.first.author.surname }} {{ activities.first.author.name }}</div>
                                <div class="post-preview-meta-details-date">{{ activities.first.date_posted }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endif %}
        <div class="row">
            {% for activity in activities|slice:"1:" %}
                <div class="col-md-6 col-xl-4 mb-5">
                    <a class="card post-preview lift h-100" href="{% url 'activity-detail' activity.id %}">
                        {% if activity.image %}
                            <img class="card-img-top background-image" src="{{ activity.image.url }}" />
                        {% else %}
                            <img class="card-img-top background-image" src="{% static 'bouygue/assets/img/activity_default.jpg' %}" />
                        {% endif %}
                        <div class="card-body-activities">
                            <h5 class="card-title">{{ activity.title }}</h5>
                            <p class="card-text-2 mt-4">Difficulté : {{ activity.get_difficulty_display }}</p>
                            <p class="card-text-2">Durée : {{ activity.duration }}</p>
                            <p class="card-text-2">Distance : {{ activity.distance }}</p>
                        </div>
                        <div class="card-footer">
                            <div class="post-preview-meta">
                                <img class="post-preview-meta-img" src="{{ activity.author.profile.image.url }}" />
                                <div class="post-preview-meta-details">
                                    <div class="post-preview-meta-details-name {% if activity.author.is_superuser or activity.author.is_staff %} text-purple {% endif %}">{{ activity.author.surname }} {{ activity.author.name }}</div>
                                    <div class="post-preview-meta-details-date">{{ activity.date_posted }}</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-blog justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item active"><a class="page-link" href="?page=1">Début</a></li>
                    <li class="page-item active"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Préc.</a></li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item disabled"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item active"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Suiv.</a></li>
                    <li class="page-item active"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Fin</a></li>
                {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
</section>
{% endblock content %}

apps/activities/templates/activities/activity-create.html
{% extends "bouygue/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block import %}
    {% include 'blocks/image-resize-imports.html' %}
{% endblock %}
<div id="layoutAuthentication_content" class="bg-img-cover" style="background-color: #1e2c41; padding-right: 0.5rem; padding-left: 0.5rem; background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/pic_har.jpg' %})">
    <div class="container" style="padding-right: 1rem; padding-left: 1rem;">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <!-- Basic registration form-->
                <div class="card shadow-lg border-0 rounded-lg mt-10 mb-5 animated--fade-in" style="opacity: 92%;">
                    <div class="card-header" style="background-color: #19273c; opacity: 96%">
                        <a onClick="javascript:history.go(-1);" class="col-xs btn btn-outline-white font-weight-bolder" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                        <div class="col-11 font-weight-700 h4 my-4 mr-2" align="center" style="color: white;">
                            Ajouter une activité
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- Post create form-->
                        <form method="POST" enctype="multipart/form-data" autocomplete="off">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <!-- Form Group (create account submit)-->
                            <div class="form-group mt-4 mb-0">
                                <button class="btn btn-primary btn-block font-weight-bolder" type="submit" name="create">Créer</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/activities/templates/activities/activity-delete.html
{% extends "bouygue/base.html" %}
{% load static %}
{% block content %}
<div id="layoutAuthentication_content" class="bg-gray-900 bg-img-cover" style="padding-right: 0.5rem; padding-left: 0.5rem; background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/panticosa.jpg' %}); height: 62rem;">
    <div class="container" style="padding-right: 1rem; padding-left: 1rem;">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <!-- Basic registration form-->
                <div class="card shadow-lg border-0 rounded-lg mt-20 mb-20 animated--fade-in" style="opacity: 92%;">
                    <div class="card-header" style="background-color: #19273c; opacity: 96%">
                        <a onClick="javascript:history.go(-1);" class="col-xs btn btn-outline-white font-weight-bolder" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                        <div class="col-11 font-weight-700 h4 my-4 mr-2" align="center" style="color: white;">
                            Supprimer l'activité
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- Delete post form-->
                        <form method="POST">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <fieldset class="form-group">
                                <h2>Etes vous sûr de vouloir supprimer cette activité ?</h2>
                            </fieldset>
                            <!-- Form Group (create account submit)-->
                            <div class="form-group mt-3 mb-1">
                                <button class="btn btn-outline-danger mt-1 font-weight-bolder" type="submit" name="delete">Oui, supprimer</button>
                                <a class="btn btn-outline-primary mt-1 font-weight-bolder" onClick="javascript:history.go(-1);">Non, annuler</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/activities/templates/activities/activity-detail.html
{% extends "bouygue/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block import %}
    {% include 'blocks/image-resize-imports.html' %}
{% endblock %}
<section class="bg-light py-10">
    <div class="container" style="padding-left: 1.5rem; padding-right: 1.5rem;">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-xl-10">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="post-archive-tag d-flex" style="margin-bottom: 2rem;">
                    <a class="btn btn-outline-primary font-weight-bolder" href="{% url 'activities' %}" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                    {% if user == activity.author %}
                    <a class="btn btn-outline-primary font-weight-700 ml-1" href="{% url 'activity-update' activity.id %}" name="update-activity">Modifier</a>
                    {% endif %}
                    {% if user == activity.author or user.is_superuser or user.is_staff %}
                    <a class="btn btn-outline-danger font-weight-700 ml-1" href="{% url 'activity-delete' activity.id %}" name="delete-activity">Supprimer</a>
                    {% endif %}
                </div>
                <div class="row d-flex">
                    <div class="col-lg-6 ml-auto">
                        <h1 class="">{{ activity.title }}</h1>
                        <div class="post-archive-meta">
                            <a href="{% url 'profile-view' activity.author.id %}"><img class="post-archive-meta-img mt-1" src="{{ activity.author.profile.image.url }}" />
                            <div class="post-archive-meta-details p-2 mt-1 mb-2">
                                <div class="post-archive-meta-details-name {% if activy.author.is_superuser or activity.author.is_staff %} text-purple {% endif %}">{{ activity.author.surname }} {{ activity.author.name }}</div></a>
                                <div class="post-archive-meta-details-date">{{ activity.date_posted }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5 ml-auto">
                        <ul class="list-group list-group-flush list-group-careers">
                            <li class="list-group-item">Difficulté : {{ activity.get_difficulty_display }}<i class="fas fa-hiking fa-fw text-gray-400"></i></li>
                            <li class="list-group-item">Durée : {{ activity.duration }}<i class="fas fa-euro-sign fa-clock text-gray-400"></i></li>
                            <li class="list-group-item">Temps de route : {{ activity.distance }}<i class="fas fa-car fa-fw text-gray-400"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="single-post">
                    {% if activity.image %}
                    <img class="img-fluid rounded mx-auto d-block mb-2" src="{{ activity.image.url }}" />
                    {% else %}
                    <img class="img-fluid rounded mx-auto d-block mb-2" src="{% static 'bouygue/assets/img/activity_default.jpg' %}" />
                    {% endif %}
                    <div class="single-post-text my-5">
                        <h4>Description</h4>
                        <p class="mb-5">{{ activity.content|linebreaks }}</p>
                        {% if activity.image2 %}
                            <img class="img-fluid rounded mx-auto d-block mb-2" src="{{ activity.image2.url }}" />
                        {% endif %}
                        {% if activity.content2 %}
                        <h4>Précisions</h4>
                        <p class="mb-5">{{ activity.content2|linebreaks }}</p>
                        {% endif %}
                    </div>
                    <hr class="my-4 mb-5" />
                </div>
            </div>
            <!-- Comment Section -->
            <div class="col-lg-10 bg-gray-200 rounded">
                <h1 class="mt-4">Commentaires</h1>
                <hr class="my-2" />
                <!-- Post Comment form-->
                <form method="POST" autocomplete="off">
                    {% csrf_token %}
                    <!-- Form Row-->
                    <fieldset class="form-group mb-5">
                        {{ form|crispy }}
                        <button class="btn btn-primary font-weight-bolder" type="submit" name="send">PUBLIER</button>
                    </fieldset>
                </form>
                {% for comment in page_obj.object_list %}
                    <div class="post-archive-meta d-flex">
                        <a href="{% url 'profile-view' comment.author.id %}"><img class="post-archive-meta-img" src="{{ comment.author.profile.image.url }}" />
                        <div class="post-archive-meta-details mr-auto p-2">
                            <div class="post-archive-meta-details-name {% if comment.author.is_superuser or comment.author.is_staff %} text-purple {% endif %}">{{ comment.author.surname }} {{ comment.author.name }}</div></a>
                            <div class="post-archive-meta-details-date">{{ comment.date_posted }}</div>
                        </div>
                        {% if user == comment.author %}
                            <a class="btn btn-outline-primary font-weight-500" style="padding: 0.6rem;" href="{% url 'activitycomment-update' comment.id %}" name="activitycomment-update">modifier</a>
                        {% endif %}
                        {% if user == comment.author or user.is_superuser or user.is_staff  %}
                            <a class="btn btn-outline-danger font-weight-500 ml-1" style="padding: 0.6rem;" href="{% url 'activitycomment-delete' comment.id %}?next={{ request.path }}" name="activitycomment-delete">supprimer</a>
                        {% endif %}
                    </div>
                    <div class="post-archive-item mt-3">
                        <p>{{ comment.content|linebreaks }}</p>
                        {% if comment.image %} <img src="{{ comment.image.url }}" class="img-fluid"/> {% endif %}
                    </div>
                    <hr class="my-5" />
                {% endfor %}
                <!-- Pagination -->
                {% if comment_count > 5 %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination pagination-blog justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item active"><a class="page-link" href="?page=1">Début</a></li>
                        <li class="page-item active"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Préc.</a></li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item disabled"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item active"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Suiv.</a></li>
                        <li class="page-item active"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Fin</a></li>
                    {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}