apps/work/urls.py
from django.urls import path
from . import views
from .views import (WorkListView, WorkDoneListView, WorkCreateView, WorkUpdateView,
                    WorkDeleteView, WorkCommentUpdateView, WorkCommentDeleteView)

urlpatterns = [
    path("work/", WorkListView.as_view(), name="work"),
    path("work/done", WorkDoneListView.as_view(), name="work-done"),
    path("work/new/", WorkCreateView.as_view(), name="work-create"),
    path("work/<int:pk>/", views.work_detail, name="work-detail"),
    path("work/<int:pk>/update/", WorkUpdateView.as_view(), name="work-update"),
    path("work/<int:pk>/delete/", WorkDeleteView.as_view(), name="work-delete"),
    path('work/comment/<int:pk>/update/',
         WorkCommentUpdateView.as_view(), name='workcomment-update'),
    path('work/comment/<int:pk>/delete/',
         WorkCommentDeleteView.as_view(), name='workcomment-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.bouygue.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.agenda.urls')),
    path('', include('apps.blog.urls')),
    path('', include('apps.activities.urls')),
    path('', include('apps.info.urls')),
    path('', include('apps.work.urls')),
    path('', include('apps.budget.urls')),
]

handler400 = 'apps.bouygue.views.bad_request'
handler403 = 'apps.bouygue.views.permission_denied'
handler404 = 'apps.bouygue.views.page_not_found'
handler500 = 'apps.bouygue.views.server_error'

apps/work/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _
from apps.users.models import MyUser


class Work(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('Titre'))
    content = models.TextField(verbose_name=_('Description'))
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    cost = models.SmallIntegerField(default=0, verbose_name=_("Coût estimé"))
    image = models.ImageField(blank=True, null=True, upload_to="work")
    categories = models.SmallIntegerField(
        default=0, choices=[(0, "Bricolage"),
                            (1, "Jardinage"), (2, "Plomberie"), (3, "Maçonnerie"), (4, "Autre")],
        verbose_name=_("Catégories")
    )
    state = models.SmallIntegerField(
        default=0,
        choices=[(0, "À faire"), (1, "En cours"), (2, "Terminé")],
        verbose_name=_("État")
    )
    status = models.SmallIntegerField(
        default=1,
        choices=[(0, "Peut attendre"), (1, "Important"), (2, "Urgent")],
        verbose_name=_("Statut")
    )

    # class Meta:
    #     ordering = ["-date_posted"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("work-detail", kwargs={"pk": self.pk})


class WorkComment(models.Model):
    content = models.TextField(verbose_name=_(''))
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="comments")

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return str(self.author)

    def get_absolute_url(self):
        return reverse("work-detail", kwargs={"pk": self.work.pk})

apps/work/forms.py
from django import forms
from .models import WorkComment
from client_side_image_cropping import ClientsideCroppingWidget


class WorkCommentForm(forms.ModelForm):
    class Meta:
        model = WorkComment
        fields = ['content', 'image']
        widgets = {
            'image': ClientsideCroppingWidget(
                width=1000,
                height=600,
                preview_width=120,
                preview_height=72,
            )
        }

apps/work/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from apps.users.models import MyUser
from .models import Work, WorkComment
from .forms import WorkCommentForm
from django.core.paginator import Paginator
from client_side_image_cropping import ClientsideCroppingWidget


class WorkListView(LoginRequiredMixin, ListView):
    model = Work
    template_name = "work/work.html"
    context_object_name = "works"
    ordering = ['-date_posted']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["handiwork"] = Work.objects.filter(categories=0).exclude(state=2)
        context["gardening"] = Work.objects.filter(categories=1).exclude(state=2)
        context["plumbing"] = Work.objects.filter(categories=2).exclude(state=2)
        context["masonry"] = Work.objects.filter(categories=3).exclude(state=2)
        context["other"] = Work.objects.filter(categories=4).exclude(state=2)
        return context

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        user.works_viewed = len(Work.objects.all())
        if user.is_authenticated and user.is_active:
            user.save()
        return super().dispatch(request, *args, **kwargs)


class WorkDoneListView(LoginRequiredMixin, ListView):
    model = Work
    template_name = "work/work-done.html"
    context_object_name = "works"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["handiwork_done"] = Work.objects.filter(categories=0).filter(state=2)
        context["gardening_done"] = Work.objects.filter(categories=1).filter(state=2)
        context["plumbing_done"] = Work.objects.filter(categories=2).filter(state=2)
        context["masonry_done"] = Work.objects.filter(categories=3).filter(state=2)
        context["other_done"] = Work.objects.filter(categories=4).filter(state=2)
        return context


@login_required()
def work_detail(request, pk):
    template_name = "work/work-detail.html"
    work = get_object_or_404(Work, pk=pk)
    author = request.user
    new_comment = None
    form = WorkCommentForm()

    if request.method == 'POST':
        if request.POST['action'] == 'comment':
            form = WorkCommentForm(data=request.POST)
            if form.is_valid():
                # Create Comment object but don't save to database yet
                new_comment = form.save(commit=False)
                # Assign the current post and author to the comment
                new_comment.work = work
                new_comment.author = author
                # Save the comment to the database
                new_comment.save()
                messages.success(request, str("Commentaire publié."))
            form = WorkCommentForm()

        elif request.POST['action'] == 'done':
            work.state = 2
            work.save()
            # Post comment saying who completed the work
            new_comment = form.save(commit=False)
            new_comment.work = work
            new_comment.author = author
            new_comment.content = "{} {} vient de signaler qu'il a terminé ce travail.".format(
                author.surname, author.name)
            messages.success(request, str("Travail terminé. Merci !"))
            new_comment.save()

    # Paginator
    comments = work.workcomment_set.all()
    comment_count = len(comments)
    paginator = Paginator(comments, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,
                  template_name,
                  {'title': 'Tâche',
                   'work': work,
                   'form': form,
                   'page_obj': page_obj,
                   'comment_count': comment_count})


class WorkCreateView(LoginRequiredMixin, CreateView):
    model = Work
    template_name = 'work/work-create.html'
    fields = ['title', 'content', 'image', 'categories', 'state', 'status', 'cost', ]

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        form.fields['image'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class WorkUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Work
    template_name = "work/work-update.html"
    fields = ["title", "content", "image", "categories", "state", "status", "cost"]

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        form.fields['image'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, str("Le travail a bien été modifié."))
        return super().form_valid(form)

    def test_func(self):
        work = self.get_object()
        user = self.request.user
        if user == work.author or user.is_superuser or user.is_staff:
            return True
        return False


class WorkDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Work
    template_name = "work/work-delete.html"
    context_object_name = "work"

    def get_success_url(self):
        messages.success(self.request, str("Le travail a bien été supprimé."))
        return "/work/"

    def test_func(self):
        work = self.get_object()
        if (
            self.request.user == work.author
            or self.request.user.is_superuser
            or self.request.user.has_perm("work.delete_work")
        ):
            return True
        return False


class WorkCommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = WorkComment
    template_name = 'work/workcomment-update.html'
    fields = ['content', 'image']

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.request = self.request
        form.fields['image'].widget = ClientsideCroppingWidget(
            width=1000,
            height=600,
            preview_width=120,
            preview_height=72,
        )
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, str("Le commentaire a bien été modifié."))
        return super().form_valid(form)

    def test_func(self):
        work = self.get_object()
        if self.request.user == work.author:
            return True
        return False


class WorkCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = WorkComment
    template_name = 'work/workcomment-delete.html'
    context_object_name = 'comment'

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            messages.success(self.request, str("Le commentaire a bien été supprimé."))
            return next_url  # return next url for redirection
        return '/work/'  # return some other url if next parameter not present

    def test_func(self):
        work = self.get_object()
        user = self.request.user
        if user == work.author or user.is_superuser or user.is_staff:
            return True
        return False

apps/work/templates/work/work-create.html
{% extends "bouygue/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block import %}
    {% include 'blocks/image-resize-imports.html' %}
{% endblock %}
<div id="layoutAuthentication_content" class="bg-gray-900 bg-img-cover" style="padding-right: 0.5rem; padding-left: 0.5rem; background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/ordesa.jpg' %});">
    <div class="container" style="padding-right: 1rem; padding-left: 1rem;">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <!-- Basic registration form-->
                <div class="card shadow-lg border-0 rounded-lg mt-10 mb-4 animated--fade-in" style="opacity: 92%;">
                    <div class="card-header" style="background-color: #19273c; opacity: 96%">
                        <a onClick="javascript:history.go(-1);" class="col-xs btn btn-outline-white font-weight-bolder" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                        <div class="col-11 font-weight-700 h4 my-4 mr-2" align="center" style="color: white;">
                            Ajouter un travail
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- Post create form-->
                        <form method="POST" autocomplete="off">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <!-- Form Group (create account submit)-->
                            <div class="form-group mt-4 mb-0">
                                <button class="btn btn-primary btn-block font-weight-bolder" type="submit" name="create">Créer</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/work/templates/work/work-delete.html
{% extends "bouygue/base.html" %}
{% load static %}
{% block content %}
<div id="layoutAuthentication_content" class="bg-gray-900 bg-img-cover" style="padding-right: 0.5rem; padding-left: 0.5rem; background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/lac_coubous.jpg' %}); height: 62rem;">
    <div class="container" style="padding-right: 1rem; padding-left: 1rem;">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <!-- Basic registration form-->
                <div class="card shadow-lg border-0 rounded-lg mt-20 mb-20 animated--fade-in" style="opacity: 92%;">
                    <div class="card-header" style="background-color: #19273c; opacity: 96%">
                        <a onClick="javascript:history.go(-1);" class="col-xs btn btn-outline-white font-weight-bolder" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                        <div class="col-11 font-weight-700 h4 my-4 mr-2" align="center" style="color: white;">
                            Supprimer le travail
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- Delete post form-->
                        <form method="POST">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <fieldset class="form-group">
                                <h2>Etes vous sûr de vouloir supprimer ce travail ?</h2>
                            </fieldset>
                            <!-- Form Group (create account submit)-->
                            <div class="form-group mt-3 mb-1">
                                <button class="btn btn-outline-danger mt-1 font-weight-bolder" type="submit" name="delete">Oui, supprimer</button>
                                <a class="btn btn-outline-primary mt-1 font-weight-bolder" onClick="javascript:history.go(-1);">Non, annuler</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/work/templates/work/work-detail.html
{% extends "bouygue/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block import %}
    {% include 'blocks/image-resize-imports.html' %}
{% endblock %}
<!-- Page Header-->
<header class="page-header page-header-dark bg-img-cover overlay overlay-60" style="background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/pic_har.jpg' %}); height: 19rem;">
    <div class="page-header-content">
        <div class="container text-center">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <h1 class="page-header-title mt-0 mb-3">Travaux</h1>
                    <p class="page-header-text mb-0">Consultez le détail d'une tâche</p>
                </div>
            </div>
        </div>
    </div>
    {% block border-wave %}
        {% include 'blocks/svg-border-wave.html' %}
    {% endblock %}
</header>
<section class="bg-light py-4 mb-5">
    <div class="container" style="padding-left: 1.5rem; padding-right: 1.5rem">
        <div class="row">
            <div class="col-lg-3">
                <ul class="list-group list-group-flush list-group-careers">
                    <li class="list-group-item pt-0">
                        <a class="small" href="{% url "work"%}" style="cursor: pointer"><i class="fas fa-arrow-left mr-1"></i>Retour</a>
                    </li>
                    <li class="list-group-item mt-2" style="border-bottom: 0; padding-bottom: 0.3rem"><h1>{{ work.title }}</h1></li>
                    <li class="list-group-item" style="padding-top: 0.3rem; justify-content: left">
                        {% if user == work.author %}
                            <a class="btn btn-outline-primary font-weight-600 mb-1" style="padding: 0.7rem;" href="{% url 'work-update' work.id %}" name="update-work">Modifier</a>
                        {% endif %}
                        {% if user == work.author or user.is_superuser or user.is_staff %}
                            <a class="btn btn-outline-danger font-weight-600 ml-1 mb-1" style="padding: 0.7rem;" href="{% url 'work-delete' work.id %}" name="delete-work">Supprimer</a>
                        {% endif %}
                    </li>
                    <li class="list-group-item">Catégorie : {{ work.get_categories_display }}<i class="fas fa-tools fa-fw text-gray-400"></i></li>
                    <li class="list-group-item">État : {{ work.get_state_display }}<i class="fas fa-calendar fa-fw text-gray-400"></i></li>
                    <li class="list-group-item">Coût estimé : {{ work.cost }} €<i class="fas fa-euro-sign fa-fw text-gray-400"></i></li>
                    <li class="list-group-item">Statut : {{ work.get_status_display }}<i class="fas fa-clock fa-fw text-gray-400"></i></li>
                </ul>
            </div>
            <div class="col-lg-9 mb-4">
                {% if messages %}
                    {% for message in messages %}
                        <div class="font-weight-400 text-center mb-4 calendar-alert alert-{{ message.tags }}" style="padding: 0.8rem">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <h5 class="mb-4">Description</h5>
                <p class="mb-4">{{ work.content|linebreaks }}</p>
                {% if work.image %} <img src="{{ work.image.url }}" class="img-fluid"/> {% endif %}
                <div class="d-flex align-items-center justify-content-between mt-4 mb-5">
                    <div class="post-archive-meta mr-4 ml-auto p-2">
                        <a href="{% url 'profile-view' work.author.id %}"><img class="post-archive-meta-img" src="{{ work.author.profile.image.url }}"/>
                        <div class="post-archive-meta-details">
                            <div class="post-archive-meta-details-name {% if work.author.is_superuser or work.author.is_staff %} text-purple {% endif %}">{{ work.author.surname }} {{ work.author.name }}</div></a>
                            <div class="post-archive-meta-details-date">{{ work.date_posted }}</div>
                        </div>
                    </div>
                </div>
                <hr class="mt-5 mb-4">
                {% if work.state != 2 %}
                <h5 class="mb-4">Signaler que cette tâche est terminée ?</h5>
                <!-- Confirmation modal -->
                <button class="btn btn-primary font-weight-bolder" type="button" data-toggle="modal" data-target="#staticBackdrop">J'ai terminé !</button>
                <div class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-md" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Attention</h5>
                                <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                            </div>
                            <div class="modal-body">
                                <p>Confirmez-vous avoir terminé ce travail ?</p>
                                <!-- Confirmation form-->
                                <form method="POST">
                                    {% csrf_token %}
                                    <!-- Form Row-->
                                    <fieldset class="form-group">
                                        <button class="btn btn-outline-red font-weight-bolder" data-dismiss="modal">Annuler</button>
                                        <button class="btn btn-outline-primary font-weight-bolder ml-1" id="confirm-done" type="submit" name="action" value="done">Confirmer</button>
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            </div>
            <!-- Comment Section -->
            <div class="col-lg-9 bg-gray-200 rounded ml-auto mt-4">
                <div class="bg-gray-200 rounded mt-5 mb-4">
                    <h1 class="mt-3">Commentaires</h1>
                    <hr class="my-2" />
                    <!-- Post Comment form-->
                    <form method="POST" autocomplete="off">
                        {% csrf_token %}
                        <!-- Form Row-->
                        <fieldset class="form-group mb-5">
                            {{ form|crispy }}
                            <button class="btn btn-primary font-weight-bolder" type="submit" name="action" value="comment">PUBLIER</button>
                        </fieldset>
                    </form>
                    {% for comment in page_obj.object_list %}
                        <div class="post-archive-meta d-flex">
                            <a href="{% url 'profile-view' comment.author.id %}"><img class="post-archive-meta-img" src="{{ comment.author.profile.image.url }}" />
                            <div class="post-archive-meta-details mr-auto p-2">
                                <div class="post-archive-meta-details-name {% if comment.author.is_superuser or comment.author.is_staff %} text-purple {% endif %}">{{ comment.author.surname }} {{ comment.author.name }}</div></a>
                                <div class="post-archive-meta-details-date">{{ comment.date_posted }}</div>
                            </div>
                            {% if user == comment.author %}
                                <a class="btn btn-outline-primary font-weight-500" style="padding: 0.6rem;" href="{% url 'workcomment-update' comment.id %}" name="workcomment-update">modifier</a>
                            {% endif %}
                            {% if user == comment.author or user.is_superuser or user.is_staff %}
                                <a class="btn btn-outline-danger font-weight-500 ml-1" style="padding: 0.6rem;" href="{% url 'workcomment-delete' comment.id %}?next={{ request.path }}" name="workcomment-delete">supprimer</a>
                            {% endif %}
                        </div>
                        <div class="post-archive-item mt-3">
                            <p>{{ comment.content|linebreaks }}</p>
                            {% if comment.image %} <img src="{{ comment.image.url }}" class="img-fluid"/> {% endif %}
                        </div>
                        <hr class="my-5" />
                    {% endfor %}
                    <!-- Pagination -->
                    {% if comment_count > 5 %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination pagination-blog justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item active"><a class="page-link" href="?page=1">Début</a></li>
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Préc.</a></li>
                        {% endif %}
                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item disabled"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Suiv.</a></li>
                            <li class="page-item active"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Fin</a></li>
                        {% endif %}
                        </ul>
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

apps/work/templates/work/work-update.html
{% extends "bouygue/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block import %}
    {% include 'blocks/image-resize-imports.html' %}
{% endblock %}
<div id="layoutAuthentication_content" class="bg-img-cover" style="padding-right: 0.5rem; padding-left: 0.5rem; background-color: #1e2c41; background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/castillou.jpg' %});">
    <div class="container" style="padding-right: 1rem; padding-left: 1rem;">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <!-- Basic registration form-->
                <div class="card shadow-lg border-0 rounded-lg mt-10 mb-4 animated--fade-in" style="opacity: 92%;">
                    <div class="card-header" style="background-color: #19273c; opacity: 96%">
                        <a onClick="javascript:history.go(-1);" class="col-xs btn btn-outline-white font-weight-bolder" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                        <div class="col-11 font-weight-700 h4 my-4 mr-2" align="center" style="color: white;">
                            Modifier le travail
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- Registration form-->
                        <form method="POST" autocomplete="off">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <!-- Form Group (create account submit)-->
                            <div class="form-group mt-4 mb-1">
                                <button class="btn btn-primary btn-block font-weight-bolder" type="submit" name="update">Modifier</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/work/templates/work/workcomment-delete.html
{% extends "bouygue/base.html" %}
{% load static %}
{% block content %}
<div id="layoutAuthentication_content" class="bg-gray-900 bg-img-cover" style="padding-right: 0.5rem; padding-left: 0.5rem; background-image: url({% static 'bouygue/assets/img/backgrounds/montagne/foratata.jpg' %}); height: 62rem;">
    <div class="container" style="padding-right: 1rem; padding-left: 1rem;">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <!-- Basic registration form-->
                <div class="card shadow-lg border-0 rounded-lg mt-20 mb-20 animated--fade-in" style="opacity: 92%;">
                    <div class="card-header" style="background-color: #19273c; opacity: 96%">
                        <a onClick="javascript:history.go(-1);" class="col-xs btn btn-outline-white font-weight-bolder" title="retour"><i class="fas fa-chevron-left dropdown-arrow"></i></a>
                        <div class="col-11 font-weight-700 h4 my-4 mr-2" align="center" style="color: white;">
                            Supprimer le commentaire
                        </div>
                    </div>
                    <div class="card-body">
                        <!-- Delete post form-->
                        <form method="POST">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <fieldset class="form-group">
                                <h2>Etes vous sûr de vouloir supprimer ce commentaire ?</h2>
                            </fieldset>
                            <!-- Form Group (create account submit)-->
                            <div class="form-group mt-3 mb-1">
                                <button class="btn btn-outline-danger mt-1 font-weight-bolder" type="submit" name="delete">Oui, supprimer</button>
                                <a class="btn btn-outline-primary mt-1 font-weight-bolder" onClick="javascript:history.go(-1);">Non, annuler</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}